# Generated by Django 3.2.9 on 2021-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idZwierze', models.IntegerField()),
                ('imie', models.TextField()),
                ('rasa', models.TextField()),
                ('rokUrodzenia', models.IntegerField()),
                ('rokPrzygarniecia', models.IntegerField()),
                ('typ', models.IntegerField()),
            ],
        ),
    ]
