# Generated by Django 3.2.9 on 2021-11-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zwierze',
            name='idZwierze',
        ),
    ]
