# Generated by Django 3.2.9 on 2021-11-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Schronisko', '0002_remove_zwierze_idzwierze'),
    ]

    operations = [
        migrations.CreateModel(
            name='magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaObiektu', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('dataZatrudnienia', models.DateField()),
                ('stanowisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaObiektu', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
                ('dataZamowienia', models.DateField()),
                ('idObiektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.magazyn')),
            ],
        ),
        migrations.CreateModel(
            name='zabieg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzajZabiegu', models.CharField(max_length=45)),
                ('idZwierze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.zwierze')),
                ('pracownicy', models.ManyToManyField(to='Schronisko.pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='datki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
                ('idObiektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schronisko.magazyn')),
            ],
        ),
    ]
