# Generated by Django 3.2.9 on 2021-12-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazyn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaObiektu', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('dataZatrudnienia', models.DateField()),
                ('stanowisko', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zwierze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('rasa', models.CharField(max_length=30)),
                ('rokUrodzenia', models.IntegerField()),
                ('rokPrzygarniecia', models.IntegerField()),
                ('typ', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaObiektu', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
                ('dataZamowienia', models.DateField()),
                ('idObiektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchroniskoAPI.magazyn')),
            ],
        ),
        migrations.CreateModel(
            name='Zabieg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzajZabiegu', models.CharField(max_length=45)),
                ('idZwierze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchroniskoAPI.zwierze')),
                ('pracownicy', models.ManyToManyField(to='SchroniskoAPI.Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Datki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('ilosc', models.IntegerField()),
                ('idObiektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchroniskoAPI.magazyn')),
            ],
        ),
    ]
