# Generated by Django 3.2.9 on 2021-12-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0003_zwierze_idadopcja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienia',
            name='idObiektu',
        ),
        migrations.DeleteModel(
            name='Datki',
        ),
        migrations.DeleteModel(
            name='Magazyn',
        ),
        migrations.DeleteModel(
            name='Zamowienia',
        ),
    ]
