# Generated by Django 3.2.9 on 2021-12-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0004_auto_20211202_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabieg',
            name='idZwierze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zwierze', to='SchroniskoAPI.zwierze'),
        ),
        migrations.AlterField(
            model_name='zwierze',
            name='idAdopcja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopcje', to='SchroniskoAPI.adopcja'),
        ),
    ]
