# Generated by Django 3.2.9 on 2021-12-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0006_alter_zwierze_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='idAdopcja',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopcje', to='SchroniskoAPI.adopcja'),
        ),
    ]
