# Generated by Django 3.2.9 on 2021-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0008_alter_zwierze_idadopcja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zwierze',
            old_name='typ',
            new_name='kot',
        ),
    ]
