# Generated by Django 3.2.9 on 2021-12-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0009_rename_typ_zwierze_kot'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabieg',
            name='dataZabiegu',
            field=models.DateField(null=True),
        ),
    ]
