# Generated by Django 3.2.9 on 2021-12-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0010_zabieg_datazabiegu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanowisko', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Stanowiska',
            },
        ),
        migrations.AlterModelOptions(
            name='adopcja',
            options={'verbose_name_plural': 'Adopcje'},
        ),
        migrations.AlterModelOptions(
            name='pracownik',
            options={'verbose_name_plural': 'Pracownicy'},
        ),
        migrations.AlterModelOptions(
            name='zabieg',
            options={'verbose_name_plural': 'Zabiegi'},
        ),
        migrations.AlterModelOptions(
            name='zwierze',
            options={'verbose_name_plural': 'Zwierzęta'},
        ),
        migrations.AlterField(
            model_name='zabieg',
            name='rodzajZabiegu',
            field=models.CharField(choices=[('operacja', 'operacja'), ('szczepienie', 'szczepienie'), ('okresowe badanie', 'okresowe badanie')], max_length=45),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='stanowisko',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanowiska', to='SchroniskoAPI.stanowisko'),
        ),
    ]
