# Generated by Django 3.2.9 on 2021-12-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0011_auto_20211212_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajeZabiegow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Rodzaje Zabiegów',
            },
        ),
    ]
