# Generated by Django 3.2.9 on 2021-12-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0012_rodzajezabiegow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabieg',
            name='rodzajZabiegu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rodzaje', to='SchroniskoAPI.rodzajezabiegow'),
        ),
    ]
