# Generated by Django 3.2.9 on 2021-12-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0013_alter_zabieg_rodzajzabiegu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zwierze',
            old_name='idAdopcja',
            new_name='data_adopcji',
        ),
        migrations.RemoveField(
            model_name='zabieg',
            name='pracownicy',
        ),
    ]
