# Generated by Django 3.2.9 on 2021-12-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0014_auto_20211212_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zwierze',
            old_name='rokPrzygarniecia',
            new_name='rok_Przygarniecia',
        ),
        migrations.RenameField(
            model_name='zwierze',
            old_name='rokUrodzenia',
            new_name='rok_Urodzenia',
        ),
    ]
