# Generated by Django 3.2.9 on 2021-12-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0015_auto_20211212_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabieg',
            name='idZwierze',
        ),
    ]
