# Generated by Django 3.2.9 on 2021-12-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0017_zabieg_idzwierze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabieg',
            name='dataZabiegu',
        ),
        migrations.RemoveField(
            model_name='zabieg',
            name='idZwierze',
        ),
        migrations.RemoveField(
            model_name='zabieg',
            name='rodzajZabiegu',
        ),
    ]
