# Generated by Django 3.2.9 on 2021-12-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0018_auto_20211217_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabieg',
            name='dataZabiegu',
            field=models.DateField(null=True),
        ),
    ]
