# Generated by Django 3.2.9 on 2021-12-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0021_auto_20211217_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabieg',
            name='zwierze',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zwierze', to='SchroniskoAPI.zwierze'),
            preserve_default=False,
        ),
    ]
