# Generated by Django 3.2.9 on 2021-12-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0024_zabieg_datazabiegu'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabieg',
            name='pracownicy',
            field=models.ManyToManyField(to='SchroniskoAPI.Pracownik'),
        ),
        migrations.AlterField(
            model_name='zabieg',
            name='zwierze',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zabieg', to='SchroniskoAPI.zwierze'),
        ),
    ]
