# Generated by Django 3.2.9 on 2022-01-07 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SchroniskoAPI', '0025_auto_20211217_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodzajezabiegow',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zabiegiUser', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stanowisko',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stanowiskaUser', to='auth.user'),
            preserve_default=False,
        ),
    ]
