# Generated by Django 3.2.9 on 2022-01-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchroniskoAPI', '0027_alter_adopcja_dataadopcji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcja',
            name='dataAdopcji',
            field=models.DateField(),
        ),
    ]
